IntexWinter2024/Views/Shared/Components/CartSummaryViewComponent.cs
using IntexWinter2024.Models;
using Microsoft.AspNetCore.Mvc;

namespace IntexWinter2024.Views.Shared.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

IntexWinter2024/Views/Shared/ProductSummary.cshtml
@model ProductCategoryViewModel

<div class="card m-1 p-1">
    <a asp-controller="Home" asp-action="ProductDetails" asp-route-productId="@Model.Product.ProductId">
        <h4>@Model.Product.Name</h4>
        <div class="row">
            <div class="col-4">
                <img src="@Model.Product.ImgLink" width="250px"/>
            </div>
            <div class="col-8">
                <ul>
                    <li>$@Model.Product.Price</li>
                    <li>@Model.Product.PrimaryColor</li>
                    <li>Year Released: @Model.Product.Year</li>
                    @if (Model.Categories.Count() == 1)
                    {
                        <li>Category: @Model.Categories.First()</li>
                    }
                    else
                    {
                        <li>Categories: @string.Join(", ", Model.Categories)</li>
                    }
                    <li>Main color: @Model.Product.PrimaryColor</li>
                </ul>
                <div class="row">
                    <div class="col-3">
                        <button asp-controller="Home" asp-action="ProductDetails" asp-route-productId="@Model.Product.ProductId" class="btn btn-secondary">View Details</button>
                    </div>
                    <div class="col-9">
                        <form id="@Model.Product.ProductId" method="post" asp-page="/Cart">
                            <input type="hidden" asp-for="@Model.Product.ProductId" name="productId" />
                            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                            <button type="submit" class="btn btn-success">Add To Cart</button>
                        </form>
                    </div>
                    
                </div>
            </div>
        </div>
    </a>
</div>

IntexWinter2024/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IntexWinter2024</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/login&register.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <a asp-controller="Home" asp-action="Index">
            <b style="font-size: xx-large; font-family: sans-serif; color: white;">Aurora's Bricks</b>
        </a>
        <nav>
            <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            <a asp-controller="Home" asp-action="Browse">Browse Kits</a>
            <a asp-controller="Home" asp-action="AboutUs">About Us</a>
            <a asp-controller="Home" asp-action="Privacy">Privacy</a>
            @if (!User.Identity.IsAuthenticated)
            {

            }
            else if (User.Identity.IsAuthenticated)
            {
                <a asp-controller="Home" asp-action="Profile" asp-route-id="@ViewData["CustomerId"]">Profile</a>
            }
          
            @if (!User.Identity.IsAuthenticated)
            {
                <a class="nav-link" asp-controller="Account" asp-action="Login">Sign in</a>
            }
            @if (User.Identity.IsAuthenticated)
            {
                <form asp-controller="Account" asp-action="Logout" method="post">
                    <button type="submit" class="btn btn-link" style="margin-left: 20px; color: white; font-family: sans-serif; font-size: large; padding: 7px 4px; margin: 7px; text-decoration:none; border: none;">
                        Logout
                    </button>
                </form>
            }
            <vc:cart-summary />
            @if (User.Identity.IsAuthenticated && ((string)ViewData["ApplicationUserRole"] == "Admin"))
            {
                <div>
                    <a asp-area="" asp-controller="Home" asp-action="AdminLandingPage"><i class="fa-solid fa-user-tie"></i></a>
                </div>
            }
        </nav>
    </header>
    <div class="render-body-container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_CookieConsentPartial" />
        </main>
    </div>

    <footer class="border-top footer text-muted" style="position: fixed; bottom: 0; width: 100%; background-color: #317287;">
        <div class="footer-container">
            &copy; 2024 - IntexWinter2024 - <a asp-area="" asp-controller="Home" asp-action="Privacy" style="color: white;">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>